[Writable]
LogLevel = 'INFO'

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[Service]
Protocol = 'http'
Host = "localhost"
Port = 49020
ServerBindAddr = '0.0.0.0'
Timeout = 45000
BootTimeout = 30000
CheckInterval = '10s'
StartupMsg = "EdgeX Thingsboard started"

[MessageQueue]
Protocol = "tcp"
Host = "localhost"
Port = 5563
Type = "zero"
Topic = "events"
[MessageQueue.Optional]
  Username =""
  Password =""
  ClientId ="edgex-thingsboard"
  Qos          =  "0"
  KeepAlive    =  "10"
  Retained     = "false"
  AutoReconnect  = "true"
  ConnectTimeout = "5"
  SkipCertVerify = "false"

[ThingsboardMQTT]
Address = "tcp://localhost:1883"
Username = "edgex-thingsboard"
ClientId = ""
Timeout = 10000

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.CoreMetadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.CoreCommand]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48082

  [Clients.SupportNotification]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

  [Clients.SupportScheduler]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48085

  [Clients.SystemMgmntAgent]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48090